# Generated by Django 4.0.5 on 2022-06-15 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='mutator_type_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='item',
            name='source_type_id',
            field=models.IntegerField(default=-1),
        ),
    ]
